name: App CI/CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/news/
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker image build --file Dockerfile --tag reza78/pirouz_app .
