name: App CI/CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: 192.168.1.13
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/news
            ./scripts/deploy.sh
